name: Disable merging

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      duration:
        description: How long to disable merging. Suffix may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
        default: '3h'
        required: true

jobs:
  disable-merging:
    runs-on: ubuntu-latest

    steps:
    - uses: octokit/request-action@v2.x
      id: enforce_admin_protection
      with:
        name: Enforce admin protection
        route: POST /repos/{repo}/branches/{branch}/protection/enforce_admins
        repo: ${{ github.repository }}
        branch: ${{ github.event.workflow_run.head_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Wait the allotted time
      uses: jakejarvis/wait-action@master
      with:
        time: '${{ github.event.inputs.duration }}'

    - uses: octokit/request-action@v2.x
      id: remove_admin_protection
      with:
        name: Removed the admin protection
        route: DELETE /repos/{repo}/branches/{branch}/protection/enforce_admins
        repo: ${{ github.repository }}
        branch: ${{ github.event.workflow_run.head_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
