# GITHUB_TOKEN is required to be set to read/write permissions (default seems to be read only): https://github.com/TheOddler/github-actions-tests/settings/actions

name: Disable merging

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      duration:
        description: How long to disable merging. Suffix may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
        default: '3h'
        required: true
      branch:
        description: What branch to protect
        default: main
        required: true

jobs:
  disable-merging:
    name: Disable Merging
    runs-on: ubuntu-latest
    steps:
    - name: Enforce admin protection
      uses: octokit/request-action@v2.1.0
      id: enforce_admin_protection
      with:
        route: POST /repos/{repo}/branches/{branch}/protection/enforce_admins
        repo: ${{ github.repository }}
        branch: ${{ github.event.inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  wait:
    name: Wait
    needs: disable-merging
    runs-on: ubuntu-latest
    steps:
    - name: Wait the allotted time
      uses: jakejarvis/wait-action@master
      with:
        time: '${{ github.event.inputs.duration }}'

  reenable-merging:
    name: Reenable Merging
    needs: wait
    runs-on: ubuntu-latest
    steps:
    - name: Removed the admin protection
      uses: octokit/request-action@v2.1.0
      id: remove_admin_protection
      with:
        route: DELETE /repos/{repo}/branches/{branch}/protection/enforce_admins
        repo: ${{ github.repository }}
        branch: ${{ github.event.inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
