# How this works:
# When running the script, it will add the `locked` protection to the first protection rule for the repo
# Then wait a bit
# Then remove the `locked` protection

# The script needs:

# 1) The first protection rule protecting the main branch
# 2) A PAT token (currently called `MY_PAT`) with enough access rights as a GitHub Secret


name: Disable merging

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      duration:
        description: How long to disable merging. Suffix may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
        default: '3h'
        required: true

jobs:

  find_protection_rule:
    name: Finding the protection rule
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    outputs:
      protection_rule_id: ${{ steps.parse_id.outputs.id }}
    steps:
    - uses: octokit/graphql-action@v2.2.1
      id: graphql_query
      with:
        query: |
          query getBranchProtectionRules($owner:String!,$repo:String!) {
            repository(owner:$owner, name:$repo) {
              branchProtectionRules(first: 1) {
                nodes {
                  pattern
                  id
                }
              }
            }
          }
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
    - name: Parse json and get ID
      id: parse_id
      run: |
        echo "id=${{ fromJson(steps.graphql_query.outputs.data).repository.branchProtectionRules.nodes[0].id }}" >> "$GITHUB_OUTPUT"


  lock_branch:
    name: Lock branch
    runs-on: ubuntu-latest
    needs: find_protection_rule
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
    - name: Lock branch
      uses: octokit/graphql-action@v2.2.1
      id: lock_branch
      with:
        query: |
          mutation lockBranch($ruleid:ID!) {
            updateBranchProtectionRule(input:{
              branchProtectionRuleId: $ruleid,
              lockBranch: true
            }) {
              branchProtectionRule {
                id
                lockBranch
              }
            }
          }
        ruleid: ${{ needs.find_protection_rule.outputs.protection_rule_id }}


  wait:
    name: Wait
    needs: lock_branch
    runs-on: ubuntu-latest
    steps:
    - name: Wait the allotted time
      uses: jakejarvis/wait-action@master
      with:
        time: '${{ github.event.inputs.duration }}'


  unlock_branch:
    name: Unlock branch
    runs-on: ubuntu-latest
    needs: [find_protection_rule, wait]
    if: always() # Run this even if "wait" fails or is cancelled, we only care that find_protection_rule succeeded
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
    - name: Lock branch
      uses: octokit/graphql-action@v2.2.1
      id: lock_branch
      with:
        query: |
          mutation lockBranch($ruleid:ID!) {
            updateBranchProtectionRule(input:{
              branchProtectionRuleId: $ruleid,
              lockBranch: false
            }) {
              branchProtectionRule {
                id
                lockBranch
              }
            }
          }
        ruleid: ${{ needs.find_protection_rule.outputs.protection_rule_id }}
