# How this works:
# When running the script, it enables the PR merge requirement so that a review by a code-owner is needed
# Most devs aren't code-owners, so PR's can't be merged.

# The script needs:

# 1) The branch to be protected: https://github.com/TheOddler/github-actions-tests/settings/branches
# 2) The setting for "Require approvals" to be enabled (otherwise it will set it to 1)
# 3) A PAT token (currently called `MY_PAT`) with enough access rights

# What would be better:
# Toggling the `locked` protection, but that can't be done through API (the API that allows setting the locked protection requires you to set a bunch of other stuff too, which I don't want to override)

# Alt: You can just manually check the `locked` toggle and all is good.

name: Disable merging

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      duration:
        description: How long to disable merging. Suffix may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
        default: '3h'
        required: true
      branch:
        description: What branch to protect
        default: main
        required: true

jobs:
  disable-merging:
    name: Disable Merging
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Enforce the admin protection
      run: |
        curl --fail-with-body -L \
          -X POST \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/graphql \
          -d ${{ echo $QUERY }}
      env:
        QUERY: |
          {
            repository(owner: "TheOddler", name: "github-actions-tests") {
              branchProtectionRules(first: 1) {
                nodes {
                  pattern
                  id
                }
              }
            }
          }

  # wait:
  #   name: Wait
  #   needs: disable-merging
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Wait the allotted time
  #     uses: jakejarvis/wait-action@master
  #     with:
  #       time: '${{ github.event.inputs.duration }}'

  # reenable-merging:
  #   name: Reenable Merging
  #   needs: wait
  #   if: always() # Run this even if "wait" fails or is cancelled
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Remove the admin protection
  #     run: |
  #       curl --fail-with-body -L \
  #         -X PATCH \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.MY_PAT }}"\
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/${{ github.repository }}/branches/${{ github.event.inputs.branch }}/protection/required_pull_request_reviews \
  #         -d '{"require_code_owner_reviews":false}'
