name: Show my PAT

on:
  # Manual trigger
  workflow_dispatch:

jobs:

  find_protection_rule:
    name: Finding the protection rule
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
    - run: |
        echo $GITHUB_TOKEN
        echo ${{ secrets.MY_PAT }}
        echo ${GITHUB_TOKEN:0:5}
        echo ${GITHUB_TOKEN:5:10}
