name: Show my Secret

on:
  # Manual trigger
  workflow_dispatch:

jobs:

  find_protection_rule:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_MAIN_SECRET }}
    steps:
    - run: |
        echo $MY_SECRET
        echo ${MY_SECRET:0:5}
        echo ${MY_SECRET:5}